FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates

COPY ./hall_request_assigner /app/hall_request_assigner

WORKDIR /app

CMD ["/app/hall_request_assigner"]